/**
 * ClusterNode - ReactFlow node component for semantic clusters
 *
 * Displays a cluster as a "Hub" (circular node) to better visualize it as a center of gravity.
 * Shows member count badge and expands on double-click.
 */

import React, { memo, useState, useCallback, useRef, useEffect } from 'react';
import PropTypes from 'prop-types';
import { Handle, Position, NodeToolbar } from 'reactflow';
import {
  Layers,
  FolderPlus,
  FolderInput,
  Download,
  ExternalLink,
  Pencil,
  Search,
  Sparkles,
  Tag
} from 'lucide-react';
import { IconButton } from '../ui';

// Hub sizing constants
const HUB_SIZE = {
  MIN_DIAMETER: 100,
  MAX_DIAMETER: 160,
  LOG_SCALE_DIVISOR: 2.5
};

const ClusterNode = memo(({ data, selected }) => {
  const [isEditingLabel, setIsEditingLabel] = useState(false);
  const [editedLabel, setEditedLabel] = useState('');
  const labelInputRef = useRef(null);
  const focusTimerRef = useRef(null);

  const isExpanded = data?.expanded || false;
  const memberCount = data?.memberCount || 0;
  const label = data?.label || 'Cluster';
  const isAutoGenerated = data?.isAutoGenerated !== false;
  const rawConfidence = data?.confidence || 'low';
  const confidence = ['high', 'medium', 'low'].includes(rawConfidence) ? rawConfidence : 'low';
  const topTerms = (data?.topTerms || data?.commonTags || []).slice(0, 3);

  // Actions
  const {
    onCreateSmartFolder,
    onMoveAllToFolder,
    onExportFileList,
    onExpand,
    onOpenAllFiles,
    onSearchWithinCluster,
    onRenameCluster,
    onTagCluster
  } = data || {};

  const handleExpandClick = useCallback(
    (e) => {
      e.stopPropagation();
      const clusterId = data?.id || data?.clusterId;
      if (clusterId && onExpand) {
        onExpand(clusterId);
      }
    },
    [onExpand, data]
  );

  const handleMenuAction = useCallback((action) => action?.(data), [data]);

  useEffect(
    () => () => {
      if (focusTimerRef.current) {
        clearTimeout(focusTimerRef.current);
        focusTimerRef.current = null;
      }
    },
    []
  );

  // Label editing
  const handleStartEditLabel = useCallback(
    (e) => {
      e?.stopPropagation();
      setEditedLabel(label);
      setIsEditingLabel(true);
      if (focusTimerRef.current) {
        clearTimeout(focusTimerRef.current);
      }
      focusTimerRef.current = setTimeout(() => {
        focusTimerRef.current = null;
        labelInputRef.current?.focus();
      }, 50);
    },
    [label]
  );

  const handleSaveLabel = useCallback(() => {
    if (editedLabel.trim() && editedLabel !== label) {
      onRenameCluster?.({ ...data, newLabel: editedLabel.trim() });
    }
    setIsEditingLabel(false);
  }, [editedLabel, label, onRenameCluster, data]);

  const handleLabelKeyDown = useCallback(
    (e) => {
      e.stopPropagation();
      if (e.key === 'Enter') handleSaveLabel();
      else if (e.key === 'Escape') setIsEditingLabel(false);
    },
    [handleSaveLabel]
  );

  // Dynamic sizing based on member count
  const scaleFactor = Math.min(1, Math.log10(memberCount + 1) / HUB_SIZE.LOG_SCALE_DIVISOR);
  const diameter = Math.round(
    HUB_SIZE.MIN_DIAMETER + scaleFactor * (HUB_SIZE.MAX_DIAMETER - HUB_SIZE.MIN_DIAMETER)
  );

  return (
    <div
      className={`
        relative rounded-full border-4 shadow-lg flex flex-col items-center justify-center
        transition-all duration-300 cursor-pointer
        ${selected ? 'scale-105 z-50' : 'hover:scale-105 z-10'}
        ${isExpanded ? 'ring-4 ring-stratosort-accent/20' : ''}
      `}
      style={{
        width: `${diameter}px`,
        height: `${diameter}px`,
        background: selected
          ? 'linear-gradient(135deg, color-mix(in srgb, var(--color-stratosort-accent) 8%, white) 0%, color-mix(in srgb, var(--color-stratosort-accent) 15%, white) 100%)'
          : 'linear-gradient(135deg, color-mix(in srgb, var(--color-stratosort-accent) 5%, white) 0%, color-mix(in srgb, var(--color-stratosort-accent) 12%, white) 100%)',
        borderColor: 'var(--color-stratosort-accent)'
      }}
      onDoubleClick={handleExpandClick}
    >
      <NodeToolbar isVisible={selected} position={Position.Top} offset={20}>
        <div className="flex gap-1 bg-white shadow-xl rounded-lg border border-system-gray-200 p-1.5 animate-in fade-in slide-in-from-bottom-2">
          {onOpenAllFiles && (
            <IconButton
              onClick={() => handleMenuAction(onOpenAllFiles)}
              size="sm"
              variant="ghost"
              className="h-7 w-7 text-system-gray-700 hover:bg-stratosort-warning/10"
              title="Open All Files"
              aria-label="Open All Files"
              icon={<ExternalLink className="w-4 h-4 text-stratosort-blue" />}
            ></IconButton>
          )}
          {onSearchWithinCluster && (
            <IconButton
              onClick={() => handleMenuAction(onSearchWithinCluster)}
              size="sm"
              variant="ghost"
              className="h-7 w-7 text-system-gray-700 hover:bg-stratosort-warning/10"
              title="Search Within"
              aria-label="Search Within"
              icon={<Search className="w-4 h-4 text-stratosort-indigo" />}
            ></IconButton>
          )}
          {onCreateSmartFolder && (
            <IconButton
              onClick={() => handleMenuAction(onCreateSmartFolder)}
              size="sm"
              variant="ghost"
              className="h-7 w-7 text-system-gray-700 hover:bg-stratosort-warning/10"
              title="Create Smart Folder"
              aria-label="Create Smart Folder"
              icon={<FolderPlus className="w-4 h-4 text-stratosort-accent" />}
            ></IconButton>
          )}
          {onMoveAllToFolder && (
            <IconButton
              onClick={() => handleMenuAction(onMoveAllToFolder)}
              size="sm"
              variant="ghost"
              className="h-7 w-7 text-system-gray-700 hover:bg-stratosort-warning/10"
              title="Move All"
              aria-label="Move All"
              icon={<FolderInput className="w-4 h-4 text-stratosort-blue" />}
            ></IconButton>
          )}
          {onExportFileList && (
            <IconButton
              onClick={() => handleMenuAction(onExportFileList)}
              size="sm"
              variant="ghost"
              className="h-7 w-7 text-system-gray-700 hover:bg-stratosort-warning/10"
              title="Export List"
              aria-label="Export List"
              icon={<Download className="w-4 h-4 text-stratosort-success" />}
            ></IconButton>
          )}
          {onTagCluster && (
            <IconButton
              onClick={() => handleMenuAction(onTagCluster)}
              size="sm"
              variant="ghost"
              className="h-7 w-7 text-system-gray-700 hover:bg-stratosort-warning/10"
              title="Tag Files"
              aria-label="Tag Files"
              icon={<Tag className="w-4 h-4 text-stratosort-purple" />}
            ></IconButton>
          )}
          {onRenameCluster && (
            <IconButton
              onClick={handleStartEditLabel}
              size="sm"
              variant="ghost"
              className="h-7 w-7 text-system-gray-700 hover:bg-stratosort-warning/10"
              title="Rename"
              aria-label="Rename"
              icon={<Pencil className="w-4 h-4 text-system-gray-500" />}
            ></IconButton>
          )}
        </div>
      </NodeToolbar>

      {/* Central Target Handle - "Hidden" in center so edges radiate from middle */}
      <Handle
        type="target"
        position={Position.Left}
        style={{
          left: '50%',
          top: '50%',
          transform: 'translate(-50%, -50%)',
          opacity: 0,
          width: 10,
          height: 10,
          background: 'transparent',
          border: 'none',
          zIndex: 0
        }}
      />

      {/* Center Icon */}
      <div
        className={`p-2.5 rounded-full mb-1.5 ${selected ? 'bg-stratosort-accent/20 text-stratosort-accent' : 'bg-stratosort-accent/10 text-stratosort-accent'}`}
      >
        <Layers className="w-8 h-8" strokeWidth={1.5} />
      </div>

      {/* Label Area */}
      <div className="text-center px-4 w-full relative z-10">
        {isEditingLabel ? (
          <input
            ref={labelInputRef}
            type="text"
            value={editedLabel}
            onChange={(e) => setEditedLabel(e.target.value)}
            onBlur={handleSaveLabel}
            onKeyDown={handleLabelKeyDown}
            onClick={(e) => e.stopPropagation()}
            className="text-xs font-semibold text-center w-full bg-white/50 border border-stratosort-accent/30 rounded-md focus:outline-none focus:border-stratosort-accent"
          />
        ) : (
          <div
            className="text-xs font-bold text-system-gray-800 line-clamp-2 leading-tight break-words group/label"
            title={label}
          >
            {label}
            {onRenameCluster && selected && (
              <Pencil
                className="w-3 h-3 text-system-gray-400 absolute -right-2 top-0 opacity-0 group-hover/label:opacity-100 cursor-pointer"
                onClick={handleStartEditLabel}
              />
            )}
          </div>
        )}
      </div>

      {/* Top terms / why (kept inside the hub to avoid clipping) */}
      {topTerms.length > 0 && (
        <div
          className="mt-1 px-5 text-center text-xs leading-snug text-stratosort-accent font-medium line-clamp-2 break-all"
          title={`Shared terms: ${topTerms.join(', ')}`}
        >
          {topTerms.join(' • ')}
        </div>
      )}

      {/* Member Count Badge */}
      <div className="absolute -top-1 -right-1 bg-white border border-stratosort-accent/30 text-stratosort-accent text-xs font-bold px-2 py-0.5 rounded-full shadow-sm flex items-center gap-1">
        <span>{memberCount}</span>
        {isAutoGenerated && <Sparkles className="w-2 h-2 text-stratosort-accent/70" />}
      </div>

      {/* Confidence Ring (Visual Indicator) */}
      <div
        className={`absolute inset-0 rounded-full border-2 opacity-30 pointer-events-none ${
          confidence === 'high'
            ? 'border-stratosort-success'
            : confidence === 'medium'
              ? 'border-stratosort-blue'
              : 'border-system-gray-300'
        }`}
        style={{ margin: '-6px' }}
      />

      {/* Central Source Handle - "Hidden" in center */}
      <Handle
        type="source"
        position={Position.Right}
        style={{
          left: '50%',
          top: '50%',
          transform: 'translate(-50%, -50%)',
          opacity: 0,
          width: 10,
          height: 10,
          background: 'transparent',
          border: 'none',
          zIndex: 0
        }}
      />
    </div>
  );
});

ClusterNode.displayName = 'ClusterNode';

ClusterNode.propTypes = {
  data: PropTypes.shape({
    id: PropTypes.string,
    clusterId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    expanded: PropTypes.bool,
    memberCount: PropTypes.number,
    label: PropTypes.string,
    confidence: PropTypes.string,
    isAutoGenerated: PropTypes.bool,
    onCreateSmartFolder: PropTypes.func,
    onMoveAllToFolder: PropTypes.func,
    onExportFileList: PropTypes.func,
    onExpand: PropTypes.func,
    onOpenAllFiles: PropTypes.func,
    onSearchWithinCluster: PropTypes.func,
    onRenameCluster: PropTypes.func,
    onTagCluster: PropTypes.func
  }),
  selected: PropTypes.bool
};

export default ClusterNode;
