/**
 * ClusterNode - ReactFlow node component for semantic clusters
 *
 * Displays a cluster as an expandable node in the graph visualization.
 * Shows cluster label, member count, confidence, and metadata preview.
 */

import React, { memo, useState, useCallback, useRef } from 'react';
import PropTypes from 'prop-types';
import { Handle, Position, NodeToolbar, NodeResizer } from 'reactflow';
import {
  Layers,
  Folder,
  FolderPlus,
  FolderInput,
  Download,
  ChevronDown,
  ChevronRight,
  Tag,
  FolderOpen,
  Sparkles,
  Search,
  ExternalLink,
  Pencil
} from 'lucide-react';
import { getConfidenceColor, CONFIDENCE_COLORS } from '../../utils/confidenceColors';

// Node sizing constants
const NODE_SIZE = {
  MIN_WIDTH: 180,
  MAX_WIDTH: 280,
  EXTRA_WIDTH_BUFFER: 40,
  LARGE_CLUSTER_THRESHOLD: 10, // Member count above which to use larger padding
  LOG_SCALE_DIVISOR: 2 // Divisor for logarithmic scale calculation
};

const ClusterNode = memo(({ data, selected }) => {
  // const [menuOpen, setMenuOpen] = useState(false); // Removed manual menu state
  const [isEditingLabel, setIsEditingLabel] = useState(false);
  const [editedLabel, setEditedLabel] = useState('');
  const labelInputRef = useRef(null);

  const isExpanded = data?.expanded || false;
  const memberCount = data?.memberCount || 0;
  const label = data?.label || 'Cluster';
  const isAutoGenerated = data?.isAutoGenerated !== false; // Default true for auto-generated labels
  // Normalize confidence to valid values with fallback
  const rawConfidence = data?.confidence || 'low';
  const confidence = ['high', 'medium', 'low'].includes(rawConfidence) ? rawConfidence : 'low';
  const dominantCategory = data?.dominantCategory;
  const commonTags = data?.commonTags || [];
  const onCreateSmartFolder = data?.onCreateSmartFolder;
  const onMoveAllToFolder = data?.onMoveAllToFolder;
  const onExportFileList = data?.onExportFileList;
  const onExpand = data?.onExpand;
  const onOpenAllFiles = data?.onOpenAllFiles;
  const onSearchWithinCluster = data?.onSearchWithinCluster;
  const onRenameCluster = data?.onRenameCluster;

  // Handle expand/collapse toggle
  const handleExpandClick = useCallback(
    (e) => {
      e.stopPropagation();
      // FIX: Validate that we have a valid cluster ID before calling onExpand
      // to prevent passing undefined to the parent handler
      const clusterId = data?.id || data?.clusterId;
      if (clusterId && onExpand) {
        onExpand(clusterId);
      }
    },
    [onExpand, data?.id, data?.clusterId]
  );

  const handleMenuAction = useCallback(
    (action) => {
      action?.(data);
    },
    [data]
  );

  // Label editing handlers
  const handleStartEditLabel = useCallback(
    (e) => {
      e?.stopPropagation();
      setEditedLabel(label);
      setIsEditingLabel(true);
      // Focus input after render
      setTimeout(() => labelInputRef.current?.focus(), 50);
    },
    [label]
  );

  const handleSaveLabel = useCallback(() => {
    if (editedLabel.trim() && editedLabel !== label) {
      onRenameCluster?.({ ...data, newLabel: editedLabel.trim() });
    }
    setIsEditingLabel(false);
  }, [editedLabel, label, onRenameCluster, data]);

  const handleCancelEditLabel = useCallback(() => {
    setIsEditingLabel(false);
    setEditedLabel('');
  }, []);

  const handleLabelKeyDown = useCallback(
    (e) => {
      e.stopPropagation();
      if (e.key === 'Enter') {
        handleSaveLabel();
      } else if (e.key === 'Escape') {
        handleCancelEditLabel();
      }
    },
    [handleSaveLabel, handleCancelEditLabel]
  );

  // Open all files in the cluster
  const handleOpenAllFiles = useCallback(
    (e) => {
      e?.stopPropagation();
      onOpenAllFiles?.(data);
    },
    [onOpenAllFiles, data]
  );

  // Search within this cluster
  const handleSearchWithinCluster = useCallback(
    (e) => {
      e?.stopPropagation();
      onSearchWithinCluster?.(data);
    },
    [onSearchWithinCluster, data]
  );

  // Scale node size based on member count using logarithmic scale for better visual distribution
  const scaleFactor = Math.min(1, Math.log10(memberCount + 1) / NODE_SIZE.LOG_SCALE_DIVISOR);
  const dynamicWidth = Math.round(
    NODE_SIZE.MIN_WIDTH + scaleFactor * (NODE_SIZE.MAX_WIDTH - NODE_SIZE.MIN_WIDTH)
  );

  // Scale padding based on cluster size
  const paddingClass = memberCount > NODE_SIZE.LARGE_CLUSTER_THRESHOLD ? 'px-5 py-4' : 'px-4 py-3';

  return (
    <div
      className={`
        ${paddingClass} rounded-xl border-2 shadow-sm
        transition-all duration-200 cursor-pointer h-full
        ${
          selected
            ? 'border-amber-500 bg-amber-50 shadow-md ring-2 ring-amber-200'
            : 'border-amber-300 bg-gradient-to-br from-amber-50 to-orange-50 hover:border-amber-400 hover:shadow-md'
        }
      `}
      style={{
        minWidth: `${dynamicWidth}px`,
        maxWidth: `${dynamicWidth + NODE_SIZE.EXTRA_WIDTH_BUFFER}px`
      }}
      onDoubleClick={handleExpandClick}
      title="Double-click to expand/collapse"
    >
      <NodeResizer
        isVisible={selected}
        minWidth={NODE_SIZE.MIN_WIDTH}
        minHeight={100}
        handleStyle={{ width: 8, height: 8, borderRadius: 2 }}
        lineStyle={{ border: '1px solid #f59e0b' }}
      />

      <NodeToolbar isVisible={selected} position={Position.Top}>
        <div className="flex gap-1 bg-white shadow-lg rounded-lg border border-gray-200 p-1">
          {onOpenAllFiles && (
            <button
              onClick={handleOpenAllFiles}
              className="p-1.5 rounded hover:bg-amber-50 text-gray-700 transition-colors"
              title="Open All Files"
            >
              <ExternalLink className="w-4 h-4 text-blue-600" />
            </button>
          )}
          {onSearchWithinCluster && (
            <button
              onClick={handleSearchWithinCluster}
              className="p-1.5 rounded hover:bg-amber-50 text-gray-700 transition-colors"
              title="Search Within Cluster"
            >
              <Search className="w-4 h-4 text-indigo-600" />
            </button>
          )}
          {onCreateSmartFolder && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                handleMenuAction(onCreateSmartFolder);
              }}
              className="p-1.5 rounded hover:bg-amber-50 text-gray-700 transition-colors"
              title="Create Smart Folder"
            >
              <FolderPlus className="w-4 h-4 text-amber-600" />
            </button>
          )}
          {onMoveAllToFolder && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                handleMenuAction(onMoveAllToFolder);
              }}
              className="p-1.5 rounded hover:bg-amber-50 text-gray-700 transition-colors"
              title="Move All to Folder"
            >
              <FolderInput className="w-4 h-4 text-blue-600" />
            </button>
          )}
          {onExportFileList && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                handleMenuAction(onExportFileList);
              }}
              className="p-1.5 rounded hover:bg-amber-50 text-gray-700 transition-colors"
              title="Export File List"
            >
              <Download className="w-4 h-4 text-green-600" />
            </button>
          )}
          {onRenameCluster && (
            <button
              onClick={handleStartEditLabel}
              className="p-1.5 rounded hover:bg-amber-50 text-gray-700 transition-colors"
              title="Rename Cluster"
            >
              <Pencil className="w-4 h-4 text-gray-500" />
            </button>
          )}
        </div>
      </NodeToolbar>

      <Handle type="target" position={Position.Left} className="!bg-amber-500 !w-2.5 !h-2.5" />

      {/* Header row with icon, label, and expand chevron */}
      <div className="flex items-center gap-2">
        <div className="p-1.5 bg-amber-100 rounded-lg">
          <Layers className="w-4 h-4 text-amber-600" />
        </div>
        <div className="flex-1 min-w-0">
          {isEditingLabel ? (
            <input
              ref={labelInputRef}
              type="text"
              value={editedLabel}
              onChange={(e) => setEditedLabel(e.target.value)}
              onBlur={handleSaveLabel}
              onKeyDown={handleLabelKeyDown}
              onClick={(e) => e.stopPropagation()}
              className="text-sm font-medium text-gray-900 w-full px-1 py-0.5 border border-amber-400 rounded bg-white focus:outline-none focus:ring-1 focus:ring-amber-500"
              placeholder="Cluster name..."
            />
          ) : (
            <div
              className="text-sm font-medium text-gray-900 truncate flex items-center gap-1 group/label"
              title={`${label}${isAutoGenerated ? ' (auto-generated)' : ''}`}
              onDoubleClick={onRenameCluster ? handleStartEditLabel : undefined}
            >
              <span className="truncate">{label}</span>
              {isAutoGenerated && (
                <Sparkles
                  className="w-3 h-3 text-amber-400 flex-shrink-0 opacity-60"
                  title="Auto-generated label"
                />
              )}
              {onRenameCluster && (
                <button
                  onClick={handleStartEditLabel}
                  className="opacity-0 group-hover/label:opacity-100 p-0.5 rounded hover:bg-amber-200/50 transition-opacity"
                  title="Rename cluster"
                >
                  <Pencil className="w-3 h-3 text-amber-600" />
                </button>
              )}
            </div>
          )}
          <div className="text-xs text-gray-500 flex items-center gap-1">
            <Folder className="w-3 h-3" />
            <span>
              {memberCount} file{memberCount !== 1 ? 's' : ''}
            </span>
          </div>
        </div>

        <button
          onClick={handleExpandClick}
          className="p-1 rounded hover:bg-amber-200/50 transition-colors text-amber-500"
          title={isExpanded ? 'Collapse cluster' : 'Expand cluster'}
          aria-label={isExpanded ? 'Collapse cluster' : 'Expand cluster'}
          aria-expanded={isExpanded}
        >
          {isExpanded ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
        </button>
      </div>

      {/* Metadata preview section */}
      <div className="mt-2 pt-2 border-t border-amber-200/50 space-y-1.5">
        {/* Confidence badge */}
        <div className="flex items-center gap-1.5">
          <span
            className={`text-[10px] px-1.5 py-0.5 rounded border ${getConfidenceColor(confidence)}`}
          >
            {CONFIDENCE_COLORS[confidence]?.dot || '○'} {confidence}
          </span>
        </div>

        {/* Dominant category */}
        {dominantCategory && (
          <div className="flex items-center gap-1 text-[11px] text-gray-600">
            <FolderOpen className="w-3 h-3 text-amber-500" />
            <span className="truncate" title={dominantCategory}>
              {dominantCategory}
            </span>
          </div>
        )}

        {/* Common tags */}
        {commonTags.length > 0 && (
          <div className="flex items-start gap-1">
            <Tag className="w-3 h-3 text-blue-400 mt-0.5 flex-shrink-0" />
            <div className="flex flex-wrap gap-1">
              {commonTags.slice(0, 3).map((tag, idx) => (
                <span
                  key={`${tag}-${idx}`}
                  className="text-[10px] px-1.5 py-0.5 bg-blue-50 text-blue-600 rounded"
                  title={tag}
                >
                  {tag.length > 12 ? `${tag.slice(0, 12)}…` : tag}
                </span>
              ))}
              {commonTags.length > 3 && (
                <span className="text-[10px] text-gray-400">+{commonTags.length - 3}</span>
              )}
            </div>
          </div>
        )}
      </div>

      <Handle type="source" position={Position.Right} className="!bg-amber-500 !w-2.5 !h-2.5" />
    </div>
  );
});

ClusterNode.displayName = 'ClusterNode';

ClusterNode.propTypes = {
  data: PropTypes.shape({
    id: PropTypes.string,
    clusterId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    expanded: PropTypes.bool,
    memberCount: PropTypes.number,
    label: PropTypes.string,
    memberIds: PropTypes.arrayOf(PropTypes.string),
    confidence: PropTypes.oneOf(['high', 'medium', 'low']),
    dominantCategory: PropTypes.string,
    commonTags: PropTypes.arrayOf(PropTypes.string),
    isAutoGenerated: PropTypes.bool,
    onCreateSmartFolder: PropTypes.func,
    onMoveAllToFolder: PropTypes.func,
    onExportFileList: PropTypes.func,
    onExpand: PropTypes.func,
    onOpenAllFiles: PropTypes.func,
    onSearchWithinCluster: PropTypes.func,
    onRenameCluster: PropTypes.func
  }),
  selected: PropTypes.bool
};

export default ClusterNode;
